/**
 * Created by DICH on 6/15/2016.
 */
exports.READY = 0;
exports.CASSANDRA_SLOW_REPORT = 1;
exports.UPDATE_QUERY_TIME = 2;
exports.COUNT_REQUEST = 3;
exports.FETCH_QUERY_TIME = 4;
exports.MINIFY_FOLDER = 5;
exports.MINIFY_FILES = 6;
exports.ADD_SECURITY_USER = 7;
exports.REMOVE_SECURITY_USER = 8;
exports.UPDATE_ELASTIC_QUERY_TIME = 9;
exports.ELASTIC_SLOW_REPORT = 10;
exports.FETCH_ELASTIC_QUERY_TIME = 11;
exports.FETCH_CASSANDRA_CONCURRENT_QUERY = 12;
exports.FETCH_RESPONSE_TIME = 13;
exports.UPDATE_RESPONSE_TIME = 14;
exports.FETCH_ELASTIC_RESPONSE_TIME = 15;
exports.UPDATE_ELASTIC_RESPONSE_TIME = 16;
exports.FETCH_ELASTIC_CONCURRENT_QUERY = 17;
exports.CALL_BROADCAST_METHOD = 18;
exports.CALL_METHOD_TO = 19;